/* BRFX — Blockbench Render FX
 * Feature Manager + Silhouette Outline Fix v1.4.0
 * MIT License — see LICENSE
 */
Plugin.register('brfx',{title:'BRFX — Render FX',author:'Yama Sung',icon:'auto_awesome',version:'1.4.0',variant:'both',min_version:'4.10.0',tags:['Rendering','Tools'],onload(){
 const plugin=this;
 plugin.outlineEnabled=false;plugin.outlineColor='#17131b';plugin.outlineThickness=0.08;plugin.outlineGroups=[];plugin.outlineSyncTimer=null;plugin.outlineMaterials=[];plugin.featureVisibility={lighting:true,skybox:true,atmosphere:true,rendering:true};
 const isBRFX=id=>typeof id==='string'&&id.indexOf('brfx_')===0;
 const safeRender=()=>{try{if(typeof Preview!=='undefined'&&Array.isArray(Preview.all))Preview.all.forEach(p=>{try{p?.render?.()}catch(e){}})}catch(e){}};
 const getId=a=>{try{return typeof a==='string'?a:a?.id||a?.action?.id||null}catch(e){return null}};
 const category=id=>{id=String(id||'').toLowerCase();if(/sky/.test(id))return'skybox';if(/fog|atmosphere|exposure|contrast|rotation/.test(id))return'atmosphere';if(/outline|toon|bloom|ambient.?occlusion|ao/.test(id))return'rendering';return'lighting'};
 const visibleActions=()=>{const out=[];try{if(typeof BarItems==='undefined')return out;Object.keys(BarItems).forEach(id=>{if(!isBRFX(id)||id==='brfx_feature_manager')return;const a=BarItems[id];if(!a)return;const key=category(id);if(plugin.featureVisibility[key]!==false)out.push(a)})}catch(e){}return out};
 const saveVisibility=()=>{try{localStorage.setItem('brfx_feature_visibility',JSON.stringify(plugin.featureVisibility))}catch(e){}};
 const loadVisibility=()=>{try{const v=JSON.parse(localStorage.getItem('brfx_feature_visibility')||'null');if(v&&typeof v==='object')Object.keys(plugin.featureVisibility).forEach(k=>{if(typeof v[k]==='boolean')plugin.featureVisibility[k]=v[k]})}catch(e){}};loadVisibility();
 const removeOutlines=()=>{try{if(plugin.outlineSyncTimer)clearInterval(plugin.outlineSyncTimer)}catch(e){}plugin.outlineSyncTimer=null;plugin.outlineGroups.forEach(g=>{try{g.parent?.remove(g)}catch(e){}});plugin.outlineGroups=[];plugin.outlineMaterials.forEach(m=>{try{m.dispose?.()}catch(e){}});plugin.outlineMaterials=[]};
 const getPreviewScenes=()=>{const out=[];try{if(typeof Preview!=='undefined'&&Array.isArray(Preview.all))Preview.all.forEach(p=>{if(p?.scene&&!out.includes(p.scene))out.push(p.scene)})}catch(e){}return out};
 const isModelMesh=o=>!!(o&&o.isMesh&&o.geometry)&&!(o.name&&String(o.name).startsWith('BRFX_'))&&!o.isGridHelper&&!o.isAxesHelper&&!o.isLine&&!o.isLineSegments;
 const makeOutlineMaterial=()=>{const mat=new THREE.MeshBasicMaterial({color:plugin.outlineColor,side:THREE.BackSide,depthWrite:false,depthTest:true,transparent:false});mat.onBeforeCompile=shader=>{shader.uniforms.brfxOutlineThickness={value:plugin.outlineThickness};shader.vertexShader='uniform float brfxOutlineThickness;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\ntransformed += objectNormal * brfxOutlineThickness;');mat.userData.brfxShader=shader};mat.needsUpdate=true;plugin.outlineMaterials.push(mat);return mat};
 const buildOutlines=()=>{removeOutlines();if(!plugin.outlineEnabled||typeof THREE==='undefined')return;let count=0;getPreviewScenes().forEach(s=>{const group=new THREE.Group();group.name='BRFX_Silhouette_Outlines';group.renderOrder=-100;const sources=[];try{s.traverse(o=>{if(isModelMesh(o))sources.push(o)})}catch(e){}sources.forEach(src=>{try{src.updateMatrixWorld(true);const mesh=new THREE.Mesh(src.geometry,makeOutlineMaterial());mesh.name='BRFX_Outline_'+count++;mesh.frustumCulled=false;mesh.matrixAutoUpdate=false;mesh.renderOrder=-100;mesh.userData.brfxSource=src;mesh.matrix.copy(src.matrixWorld);mesh.visible=src.visible!==false;group.add(mesh)}catch(e){}});if(group.children.length){s.add(group);plugin.outlineGroups.push(group)}});if(plugin.outlineGroups.length)plugin.outlineSyncTimer=setInterval(()=>{if(!plugin.outlineEnabled||plugin._core?.brfxEnabled===false){removeOutlines();return}plugin.outlineGroups.forEach(g=>g.children.forEach(o=>{const src=o.userData?.brfxSource;if(!src)return;try{src.updateMatrixWorld(true);o.matrix.copy(src.matrixWorld);o.visible=src.visible!==false}catch(e){}}))},50);safeRender()};
 const openOutline=()=>{try{if(plugin._core?.brfxEnabled===false){Blockbench.showQuickMessage('BRFX is off — turn it on first',1800);return}if(plugin.outlineDialog){plugin.outlineDialog.show();return}plugin.outlineDialog=new Dialog({id:'brfx_outline_settings',title:'BRFX — Silhouette Outlines',form:{enabled:{label:'Enable Silhouette Outlines',type:'checkbox',value:plugin.outlineEnabled},color:{label:'Outline Color',type:'color',value:plugin.outlineColor},thickness:{label:'Outline Thickness',type:'number',value:plugin.outlineThickness,min:.01,max:.5,step:.01}},onConfirm(f){plugin.outlineEnabled=!!f.enabled;plugin.outlineColor=f.color&&typeof f.color.toHexString==='function'?f.color.toHexString():String(f.color||plugin.outlineColor);plugin.outlineThickness=Math.max(.01,Math.min(.5,Number(f.thickness)||.08));buildOutlines()}});plugin.outlineDialog.show()}catch(e){console.error(e);Blockbench.showQuickMessage('BRFX: outline settings failed',2500)}};
 const openFeatureManager=()=>{try{if(plugin._core?.brfxEnabled===false){Blockbench.showQuickMessage('BRFX is off — turn it on first',1800);return}const form={lighting:{label:'Lighting Features',type:'checkbox',value:plugin.featureVisibility.lighting},skybox:{label:'Skybox Features',type:'checkbox',value:plugin.featureVisibility.skybox},atmosphere:{label:'Atmosphere Features',type:'checkbox',value:plugin.featureVisibility.atmosphere},rendering:{label:'Rendering Features',type:'checkbox',value:plugin.featureVisibility.rendering}};new Dialog({id:'brfx_feature_manager_settings',title:'BRFX — Feature Manager',form,onConfirm(f){Object.keys(form).forEach(k=>plugin.featureVisibility[k]=!!f[k]);saveVisibility();refreshMenu();Blockbench.showQuickMessage('BRFX feature visibility updated',1400)}}).show()}catch(e){console.error(e);Blockbench.showQuickMessage('BRFX: feature manager failed',2500)}};
 const refreshMenu=()=>{try{const tools=MenuBar?.menus?.tools;if(!tools||!Array.isArray(tools.structure))return;const idx=tools.structure.findIndex(x=>getId(x)==='brfx_menu');if(idx<0)return;tools.structure[idx]={id:'brfx_menu',name:'BRFX',icon:'auto_awesome',children:()=>{const settings=new Action('brfx_feature_manager_item',{name:'⚙ Feature Settings',icon:'settings',click:openFeatureManager});const acts=visibleActions().filter(a=>a.id!=='brfx_feature_manager_item');return[settings,...acts]}};try{tools.update?.()}catch(e){}}catch(e){console.error('BRFX menu refresh failed',e)}};
 const organizeMenu=()=>{try{const tools=MenuBar?.menus?.tools;if(!tools||!Array.isArray(tools.structure))return;tools.structure=tools.structure.filter(item=>{const id=getId(item);return id!=='brfx_menu'&&!isBRFX(id)});tools.structure.push({id:'brfx_menu',name:'BRFX',icon:'auto_awesome',children:()=>{const settings=new Action('brfx_feature_manager_item',{name:'⚙ Feature Settings',icon:'settings',click:openFeatureManager});return[settings,...visibleActions()]}});try{tools.update?.()}catch(e){}}catch(e){console.error('BRFX menu organization failed',e)}};
 const runCore=src=>{try{const start=src.indexOf("Plugin.register('brfx'");const alt=src.indexOf('Plugin.register(\"brfx\"');const at=start>=0?start:alt;if(at<0)throw Error('core registration not found');const openBrace=src.indexOf('{',at);const end=src.lastIndexOf('});');if(openBrace<0||end<openBrace)throw Error('core bounds not found');const obj=src.slice(openBrace,end+1);const core=new Function('return '+obj)();core.onload?.call(core);plugin._core=core;plugin.brfxEnabled=true;const oldUnload=core.onunload;core.onunload=function(r=false){removeOutlines();return oldUnload?.call(core,r)};const oldApply=core.applyAll;if(typeof oldApply==='function')core.applyAll=function(show=true){if(plugin.brfxEnabled===false){removeOutlines();return null}const r=oldApply.call(core,show);if(plugin.outlineEnabled)buildOutlines();return r};organizeMenu();removeOutlines();Blockbench.showQuickMessage('BRFX 1.4.0 loaded',1500)}catch(e){console.error('BRFX core load failed',e);Blockbench.showQuickMessage('BRFX: core load failed — '+(e?.message||e),3500)}};
 const url='https://raw.githubusercontent.com/yamasung7-dot/BRFX/691d0aaeebe6729f1d575d8eef50d79a73d66167/brfx.js';
 const fail=e=>{console.error('BRFX: core fetch failed',e);Blockbench.showQuickMessage('BRFX: could not load core — '+(e?.message||'network error'),3500)};
 const loadWithAjax=()=>{try{if(typeof $!=='undefined'&&typeof $.ajax==='function'){$.ajax({url:url+'?brfx=1.4.0',cache:false,dataType:'text',success:runCore,error:(xhr,status,error)=>fail(error||status)});return true}}catch(e){fail(e)}return false};
 try{if(typeof fetch==='function'){const timer=new Promise((_,rej)=>setTimeout(()=>rej(Error('fetch timeout')),8000));Promise.race([fetch(url+'?brfx=1.4.0',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.text()}),timer]).then(runCore).catch(e=>{if(!loadWithAjax())fail(e)})}else if(!loadWithAjax())fail(Error('no supported network loader'))}catch(e){if(!loadWithAjax())fail(e)}
 },onunload(){try{this.outlineEnabled=false;removeOutlines?.();this.featureManagerAction?.delete?.();this.outlineDialog?.hide?.();this._core?.onunload?.call(this._core,false)}catch(e){}}});