/* BRFX — Blockbench Render FX
 * Reload Compatibility Pass v1.3.3
 * MIT License — see LICENSE
 */
Plugin.register('brfx',{title:'BRFX — Render FX',author:'Yama Sung',icon:'auto_awesome',version:'1.3.3',variant:'both',min_version:'4.10.0',tags:['Rendering','Tools'],onload(){
 const plugin=this; plugin.outlineEnabled=false; plugin.outlineColor='#17131b'; plugin.outlineThickness=0.08; plugin.outlineGroup=null; plugin.outlineSyncTimer=null; plugin.outlineMaterials=[];
 const cleanup=()=>{try{if(typeof BarItems!=='undefined')Object.keys(BarItems).forEach(id=>{if(String(id).indexOf('brfx_outline_')===0)try{BarItems[id]?.delete?.()}catch(e){}})}catch(e){}}; cleanup();
 const removeOutlines=()=>{try{if(plugin.outlineSyncTimer)clearInterval(plugin.outlineSyncTimer)}catch(e){} plugin.outlineSyncTimer=null; try{plugin.outlineGroup?.parent?.remove(plugin.outlineGroup)}catch(e){} plugin.outlineGroup=null; plugin.outlineMaterials.forEach(m=>{try{m.dispose?.()}catch(e){}}); plugin.outlineMaterials=[]};
 const sceneOf=()=>{try{if(typeof scene!=='undefined'&&scene)return scene}catch(e){}try{if(window.scene)return window.scene}catch(e){}return null};
 const isMesh=o=>!!(o&&o.isMesh&&o.geometry)&&!(o.name&&String(o.name).startsWith('BRFX_'))&&!o.isGridHelper&&!o.isAxesHelper&&!o.isLine&&!o.isLineSegments&&o.type!=='GridHelper'&&o.type!=='AxesHelper';
 const build=()=>{removeOutlines();if(!plugin.outlineEnabled||typeof THREE==='undefined')return;const s=sceneOf();if(!s)return;const group=new THREE.Group();group.name='BRFX_Silhouette_Outlines';group.renderOrder=-10;const sources=[];try{s.traverse(o=>{if(isMesh(o))sources.push(o)})}catch(e){} sources.forEach((src,i)=>{try{const mat=new THREE.MeshBasicMaterial({color:plugin.outlineColor,side:THREE.BackSide,depthWrite:false,depthTest:true});mat.onBeforeCompile=sh=>{sh.uniforms.brfxOutlineThickness={value:plugin.outlineThickness};sh.vertexShader='uniform float brfxOutlineThickness;\n'+sh.vertexShader;sh.vertexShader=sh.vertexShader.replace('#include <project_vertex>','transformed += objectNormal * brfxOutlineThickness;\n#include <project_vertex>')};mat.needsUpdate=true;plugin.outlineMaterials.push(mat);const o=new THREE.Mesh(src.geometry,mat);o.name='BRFX_Outline_'+i;o.frustumCulled=false;o.matrixAutoUpdate=false;o.renderOrder=-10;o.userData.brfxSource=src;o.matrix.copy(src.matrixWorld);o.visible=src.visible!==false;group.add(o)}catch(e){}});if(group.children.length)s.add(group);plugin.outlineGroup=group;plugin.outlineSyncTimer=setInterval(()=>{if(!plugin.outlineEnabled||plugin._core?.brfxEnabled===false){removeOutlines();return}group.children.forEach(o=>{const src=o.userData?.brfxSource;if(!src)return;try{src.updateMatrixWorld(true);o.matrix.copy(src.matrixWorld);o.visible=src.visible!==false}catch(e){}})},50)};
 const open=()=>{try{if(plugin._core?.brfxEnabled===false){Blockbench.showQuickMessage('BRFX is off — turn it on first',1800);return}if(plugin.dialog){plugin.dialog.show();return}plugin.dialog=new Dialog({id:'brfx_outline_settings',title:'BRFX — Silhouette Outlines',form:{enabled:{label:'Enable Silhouette Outlines',type:'checkbox',value:false},color:{label:'Outline Color',type:'color',value:plugin.outlineColor},thickness:{label:'Outline Thickness',type:'number',value:plugin.outlineThickness,min:.01,max:.5,step:.01}},onConfirm(f){plugin.outlineEnabled=!!f.enabled;plugin.outlineColor=f.color&&typeof f.color.toHexString==='function'?f.color.toHexString():String(f.color||plugin.outlineColor);plugin.outlineThickness=Math.max(.01,Math.min(.5,Number(f.thickness)||.08));build();try{Preview?.all?.forEach(p=>p?.render?.())}catch(e){}}});plugin.dialog.show()}catch(e){console.error(e);Blockbench.showQuickMessage('BRFX: outline settings failed',2500)}};
 const makeOutlineAction=()=>{try{const a=new Action('brfx_outline_settings',{name:'BRFX — Silhouette Outlines',icon:'border_outer',click:open});if(typeof MenuBar!=='undefined'&&MenuBar.menus?.tools)MenuBar.menus.tools.addAction(a);plugin._outlineAction=a}catch(e){console.error('BRFX outline action failed',e)}};
 const organizeMenu=()=>{try{const tools=MenuBar?.menus?.tools;if(!tools||!Array.isArray(tools.structure))return;const items=[];tools.structure=tools.structure.filter(item=>{const id=typeof item==='string'?item:item?.id;if(id==='brfx_menu')return false;if(typeof id==='string'&&id.indexOf('brfx_')===0){const action=typeof item==='string'?(typeof BarItems!=='undefined'?BarItems[item]:null):item;if(action)items.push(action);return false}return true});if(plugin._outlineAction&&items.indexOf(plugin._outlineAction)<0)items.push(plugin._outlineAction);if(items.length){tools.structure.push({id:'brfx_menu',name:'BRFX',icon:'auto_awesome',children:items});try{tools.update?.()}catch(e){}}}catch(e){console.error('BRFX menu organization failed',e)}};
 const runCore=src=>{try{const start=src.indexOf("Plugin.register('brfx'");const alt=src.indexOf('Plugin.register("brfx"');const at=start>=0?start:alt;if(at<0)throw Error('core registration not found');const openBrace=src.indexOf('{',at);const end=src.lastIndexOf('});');if(openBrace<0||end<openBrace)throw Error('core bounds not found');const obj=src.slice(openBrace,end+1);const core=new Function('return '+obj)();core.onload?.call(core);plugin._core=core;plugin.brfxEnabled=true;const oldUnload=core.onunload;core.onunload=function(r=false){removeOutlines();return oldUnload?.call(core,r)};const oldApply=core.applyAll;if(typeof oldApply==='function')core.applyAll=function(show=true){if(plugin.brfxEnabled===false){removeOutlines();return null}const r=oldApply.call(core,show);if(plugin.outlineEnabled)build();return r};organizeMenu();removeOutlines();Blockbench.showQuickMessage('BRFX 1.3.3 loaded',1500)}catch(e){console.error('BRFX core load failed',e);Blockbench.showQuickMessage('BRFX: core load failed — '+(e?.message||e),3500)}};
 const url='https://raw.githubusercontent.com/yamasung7-dot/BRFX/691d0aaeebe6729f1d575d8eef50d79a73d66167/brfx.js';
 const fail=e=>{console.error('BRFX: core fetch failed',e);Blockbench.showQuickMessage('BRFX: could not load core — '+(e?.message||'network error'),3500)};
 const loadWithAjax=()=>{try{if(typeof $!=='undefined'&&typeof $.ajax==='function'){$.ajax({url:url+'?brfx=1.3.3',cache:false,dataType:'text',success:runCore,error:(xhr,status,error)=>fail(error||status)});return true}}catch(e){fail(e)}return false};
 makeOutlineAction();
 try{if(typeof fetch==='function'){const timer=new Promise((_,rej)=>setTimeout(()=>rej(Error('fetch timeout')),8000));Promise.race([fetch(url+'?brfx=1.3.3',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.text()}),timer]).then(runCore).catch(e=>{if(!loadWithAjax())fail(e)})}else if(!loadWithAjax())fail(Error('no supported network loader'))}catch(e){if(!loadWithAjax())fail(e)}
 },onunload(){try{this.outlineEnabled=false;this.outlineSyncTimer&&clearInterval(this.outlineSyncTimer);this.outlineGroup?.parent?.remove(this.outlineGroup);this.outlineMaterials.forEach(m=>m.dispose?.());this.outlineMaterials=[];this._core?.onunload?.call(this._core,false);this._outlineAction?.delete?.()}catch(e){}}});