/* BRFX — Blockbench Render FX
 * Reload Lifecycle Stabilization Pass v1.5.7
 * MIT License — see LICENSE
 */
Plugin.register('brfx',{title:'BRFX — Render FX',author:'Yama Sung',icon:'auto_awesome',version:'1.5.7',variant:'both',min_version:'4.10.0',tags:['Rendering','Tools'],onload(){
 const plugin=this;plugin._core=null;plugin._featureActions={};plugin.featureVisibility={lighting:true,skybox:true,atmosphere:true,rendering:true};plugin._originalQuickMessage=null;plugin.toonEnabled=false;plugin.toonBands=4;plugin.toonStrength=0.85;plugin.toonMaterials=[];plugin._loading=true;
 const coreUrl='https://raw.githubusercontent.com/yamasung7-dot/BRFX/638b0e2d6673c93153136d1f660b193c185b0b1d/brfx.js';
 const keys=['lighting','skybox','atmosphere','rendering'];
 const mergedNames=['brfx — warm sun','brfx — neutral daylight','brfx — moonlight'];const mergedIds=['brfx_warm','brfx_neutral','brfx_moon'];
 const categoryNames={lighting:'Lighting',skybox:'Skybox',atmosphere:'Atmosphere',rendering:'Rendering'};
 const loadState=()=>{try{const v=JSON.parse(localStorage.getItem('brfx_feature_visibility')||'null');if(v)keys.forEach(k=>{if(typeof v[k]==='boolean')plugin.featureVisibility[k]=v[k]})}catch(e){}};
 const saveState=()=>{try{localStorage.setItem('brfx_feature_visibility',JSON.stringify(plugin.featureVisibility))}catch(e){}};loadState();
 const idOf=x=>typeof x==='string'?x:x?.id||x?.action?.id||'';const isBRFX=id=>String(id||'').startsWith('brfx_');
 const category=id=>{id=String(id||'').toLowerCase();if(/sky/.test(id))return'skybox';if(/fog|atmosphere|exposure|contrast|rotation/.test(id))return'atmosphere';if(/outline|toon|bloom|ambient.?occlusion|ao/.test(id))return'rendering';return'lighting'};
 const isMergedPreset=a=>{const id=String(a?.id||'').toLowerCase();const name=String(a?.name||a?.label||'').toLowerCase();return mergedIds.includes(id)||mergedNames.includes(name)};
 const collect=()=>{try{if(typeof BarItems==='undefined')return;Object.keys(BarItems).forEach(id=>{if(!isBRFX(id)||['brfx_menu','brfx_feature_manager','brfx_feature_manager_item'].includes(id))return;const a=BarItems[id];if(a&&typeof a.click==='function'&&!isMergedPreset(a))plugin._featureActions[id]=a})}catch(e){}};
 const removeStale=()=>{try{if(typeof BarItems==='undefined')return;Object.keys(BarItems).forEach(id=>{if(!isBRFX(id)||['brfx_menu','brfx_feature_manager','brfx_feature_manager_item'].includes(id))return;const a=BarItems[id];if(a&&isMergedPreset(a))a.delete?.()})}catch(e){}};
 const cleanTools=()=>{try{const tools=MenuBar?.menus?.tools;if(!tools||!Array.isArray(tools.structure))return;tools.structure=tools.structure.filter(x=>!isBRFX(idOf(x)));tools.update?.(true)}catch(e){}};
 const visibleActions=()=>Object.keys(plugin._featureActions).filter(id=>plugin.featureVisibility[category(id)]!==false).map(id=>plugin._featureActions[id]).filter(a=>a&&!isMergedPreset(a));
 const openManager=()=>{try{if(plugin._core?.brfxEnabled===false){Blockbench.showQuickMessage('BRFX is off — turn it on first',1800);return}new Dialog({id:'brfx_feature_manager_157',title:'BRFX — Feature Settings',form:{lighting:{label:'Lighting Features',type:'checkbox',value:plugin.featureVisibility.lighting},skybox:{label:'Skybox Features',type:'checkbox',value:plugin.featureVisibility.skybox},atmosphere:{label:'Atmosphere Features',type:'checkbox',value:plugin.featureVisibility.atmosphere},rendering:{label:'Rendering Features',type:'checkbox',value:plugin.featureVisibility.rendering}},onConfirm(f){keys.forEach(k=>plugin.featureVisibility[k]=!!f[k]);saveState();buildMenu();Blockbench.showQuickMessage('BRFX feature visibility updated',1400)}}).show()}catch(e){console.error(e);Blockbench.showQuickMessage('BRFX: Feature Settings failed',2500)}};
 const buildMenu=()=>{collect();removeStale();cleanTools();try{const tools=MenuBar?.menus?.tools;if(!tools||!Array.isArray(tools.structure))return;const settings=new Action('brfx_feature_manager_item',{name:'⚙ Feature Settings',icon:'settings',click:openManager});const groups={lighting:[],skybox:[],atmosphere:[],rendering:[]};visibleActions().forEach(a=>{const k=category(a.id);if(groups[k])groups[k].push(a)});const items=[settings];keys.forEach(k=>{if(groups[k].length)items.push({id:'brfx_category_'+k,name:categoryNames[k],icon:k==='lighting'?'light_mode':k==='skybox'?'cloud':k==='atmosphere'?'cloud_queue':'auto_awesome',children:groups[k]})});tools.structure.push({id:'brfx_menu',name:'BRFX',icon:'auto_awesome',children:items});tools.update?.(true)}catch(e){console.error('BRFX menu build failed',e)}};
 const findMeshes=()=>{const out=[];try{if(typeof Preview!=='undefined'&&Array.isArray(Preview.all))Preview.all.forEach(p=>{const s=p?.scene;if(!s)return;s.traverse?.(o=>{if(o?.isMesh&&!String(o.name||'').startsWith('BRFX_'))out.push(o)})})}catch(e){}return out};
 const applyToon=()=>{if(plugin._core?.brfxEnabled===false)return;removeToon();const bands=Math.max(2,Math.min(8,Math.round(plugin.toonBands)));const strength=Math.max(0,Math.min(1,Number(plugin.toonStrength)||0.85));findMeshes().forEach(mesh=>{const mats=Array.isArray(mesh.material)?mesh.material:[mesh.material];mats.forEach(material=>{if(!material||!material.isMaterial)return;const original=material.onBeforeCompile;const originalKey=material.customProgramCacheKey;const wrapper=(shader,renderer)=>{if(typeof original==='function')original.call(material,shader,renderer);shader.fragmentShader=shader.fragmentShader.replace('#include <output_fragment>','float brfx_luma=dot(outgoingLight,vec3(0.2126,0.7152,0.0722)); float brfx_step=floor(brfx_luma*'+bands+'.0)/'+bands+'.0; float brfx_mix=mix(brfx_luma,brfx_step,'+strength+'); float brfx_scale=brfx_luma>0.0001?brfx_mix/brfx_luma:1.0; outgoingLight*=brfx_scale; #include <output_fragment>')};material.userData=material.userData||{};material.userData.brfxToonOriginal=original;material.userData.brfxToonOriginalKey=originalKey;material.userData.brfxToonWrapper=wrapper;material.onBeforeCompile=wrapper;material.customProgramCacheKey=()=>String(originalKey?.call(material)||'')+'|BRFX_TOON_'+bands+'_'+Math.round(strength*100);material.needsUpdate=true;plugin.toonMaterials.push(material)})})};
 const removeToon=()=>{plugin.toonMaterials.forEach(material=>{try{if(!material)return;const d=material.userData||{};if(d.brfxToonWrapper&&material.onBeforeCompile===d.brfxToonWrapper)material.onBeforeCompile=d.brfxToonOriginal||function(){};material.customProgramCacheKey=d.brfxToonOriginalKey||undefined;delete d.brfxToonWrapper;delete d.brfxToonOriginal;delete d.brfxToonOriginalKey;material.needsUpdate=true}catch(e){}});plugin.toonMaterials=[]};
 const openToonSettings=()=>{try{if(plugin._core?.brfxEnabled===false){Blockbench.showQuickMessage('BRFX is off — turn it on first',1800);return}new Dialog({id:'brfx_toon_settings',title:'BRFX — Toon Shading',form:{enabled:{label:'Enable Toon Shading',type:'checkbox',value:plugin.toonEnabled},bands:{label:'Shading Bands',type:'number',value:plugin.toonBands,min:2,max:8,step:1},strength:{label:'Toon Strength',type:'number',value:plugin.toonStrength,min:0,max:1,step:0.05}},onConfirm(f){plugin.toonEnabled=!!f.enabled;plugin.toonBands=Number(f.bands)||4;plugin.toonStrength=Number(f.strength);if(plugin.toonEnabled)applyToon();else removeToon();Blockbench.showQuickMessage(plugin.toonEnabled?'BRFX Toon Shading enabled':'BRFX Toon Shading disabled',1600)}}).show()}catch(e){console.error(e);Blockbench.showQuickMessage('BRFX: Toon Shading failed',2500)}};
 const installReloadGuard=()=>{try{if(typeof Blockbench==='undefined'||typeof Blockbench.showQuickMessage!=='function')return;const original=Blockbench.showQuickMessage;if(plugin._originalQuickMessage)return;plugin._originalQuickMessage=original;Blockbench.showQuickMessage=function(message,...args){if(typeof message==='string'&&/^BRFX\s+\d+\.\d+\.\d+\s+(loaded|reload complete)$/.test(message))return;return original.call(this,message,...args)}}catch(e){}};
 const runCore=src=>{try{installReloadGuard();const at=Math.max(src.indexOf("Plugin.register('brfx'"),src.indexOf('Plugin.register("brfx"'));if(at<0)throw Error('core registration not found');const open=src.indexOf('{',at),end=src.lastIndexOf('});');if(open<0||end<open)throw Error('core bounds not found');const core=new Function('return '+src.slice(open,end+1))();core.onload?.call(core);plugin._core=core;plugin.brfxEnabled=true;const oldUnload=core.onunload;core.onunload=function(r=false){removeToon();return oldUnload?.call(core,r)};const oldApply=core.applyAll;if(typeof oldApply==='function')core.applyAll=function(show=true){if(plugin.brfxEnabled===false)return null;const result=oldApply.call(core,show);if(plugin.toonEnabled)applyToon();return result};buildMenu();setTimeout(()=>{collect();buildMenu()},500);setTimeout(()=>{collect();buildMenu();plugin._loading=false;Blockbench.showQuickMessage('BRFX 1.5.7 ready',1800)},1300)}catch(e){console.error('BRFX core load failed',e);plugin._loading=false;Blockbench.showQuickMessage('BRFX: core load failed — '+(e?.message||e),3500)}};
 const fail=e=>{console.error('BRFX core fetch failed',e);plugin._loading=false;Blockbench.showQuickMessage('BRFX: could not load core',3500)};
 const ajax=()=>{try{if(typeof $!=='undefined'&&typeof $.ajax==='function'){$.ajax({url:coreUrl,cache:false,dataType:'text',success:runCore,error:(x,s,e)=>fail(e||s)});return true}}catch(e){fail(e)}return false};
 try{if(typeof fetch==='function'){const timeout=new Promise((_,r)=>setTimeout(()=>r(Error('fetch timeout')),8000));Promise.race([fetch(coreUrl,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.text()}),timeout]).then(runCore).catch(e=>{if(!ajax())fail(e)})}else if(!ajax())fail(Error('no network loader'))}catch(e){if(!ajax())fail(e)}
 },onunload(){try{this._loading=false;this.brfxEnabled=false;removeToon?.();this._core?.onunload?.call(this._core,false);this._featureActions={};const tools=MenuBar?.menus?.tools;if(tools&&Array.isArray(tools.structure)){tools.structure=tools.structure.filter(x=>!String(idOf(x)).startsWith('brfx_'));tools.update?.(true)}}catch(e){}try{if(this._originalQuickMessage)Blockbench.showQuickMessage=this._originalQuickMessage}catch(e){}}});